language: python
python:
- 3.6
- 3.5
- 3.4
- 2.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: yulkes
  password:
    secure: QcgRHGmZkrNG6SxHmv93Clkgx9j4NHOClWpb6P752zQHiltFE9SFaQB/6ikVChMVVINhXWJrU6gVN0jUHeApgRfmj4EaIEHZHw0LfY/AGUGVBstacb/xK9PoJcHTXb93gltnVljBTULKaU/93ksfZN05NY5DA5xxyZYhMhC4H6g5ZIgPRBO7hGdUNBBTV6akNyGusQEFlc6F+bsfkbJLhz18o1QHSHe904aS9oQJy24bQyn+dyjY1TyOQBNJSWX8fwg6bkV8kiNuuj0o+Azb/Kl9SXJzGg5sqoZNvea5AmKbAwgnsDBfSER3qB1Wg8qLrUeGOguIWKPfIFCDYHMipWYz0fWzWDma9kL5KJi0mZUdFG2AZ003MYs2cszn6rT1uhqrn//mbKTzW0h1CJotlM+qKu5mMc02MCNjWr1V5u5pTmLFy3+pJ+F9q/W3N74vx2W82QUdlVvrTpDz7R9uur2MlAHstQk2Y8Rr6nJUnwvCF209+LoD4T+YXv2kQ2VUVC7W7MkTzL+2gl71/O0iTa0t44sDekBjRvP974CNVTS+RtIksrC5hKYvpqbkeZsR83u+wDaOH7pQe8kYb7896E4d8uJEgDzHp27tlQK6Ky/mogNTD0CE2DA/zJYvWgSwJsBTYq+n7jop2bbqWoTtMyoR2wSVvEmFY1pjFJq4N7M=
  on:
    tags: true
    repo: yulkes/image-builder-lib
    python: 3.6
