language: python
python:
- 3.6
- 3.5
- 3.4
- 2.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: yulkes
  password:
    secure: J5hD0k36ZWUkcvHIH0gk75Tsk05eWeYJZBCXQAOw1dSPIKzzk+Z1AFFZ6TL1g6HuoXKnaEIg1IVHsL6US5I0SMq6l4F0juC0S8KBl8heD4lfde/P2oFCB84gLFUB1R7e7uHHpv0KvZc4/kvgc7jQF3O2EGULzrE8F55gTp5kbUHmlgNt/K4VsdRU46rPul7RNp9giy5+aLLSpbdW23zUEJK6nNFdB227mJt9+Ndmsh3k5lWXzIJ1KSwuPr0cw1pu7rOR2kfZfXqlQZgOQj0lTgvcFqL98ByLaFxXK137t8OyIiyICMAMa0Colql+Wxf3j+Z2Qx523lq0b3NceQnn9wvX2asR4JlM99PcgWedbiujmeqguveGHFC2hVtR3+FKTcmISIHJ7fbglzr4aNZCNvwKHx+OD1J0mDp3/VC/okDr3+nM2vbEaPuzRKaINJJRNyoIEB0K8NpZsIICsGOsWjvbRAK54/wkUgECRfXn1JjLLFeJLa9F7olMYISQNqC731+AnkSiUT1JNkYRMN95zfwdiJcf5S9IYfH+tH4m/B4Uprp34GzCsuiIs9JPZi848lUrGILMzzKq3AmKbdeQcjxiKA2cCR4uSmc3I+ziiY6AqE7aJsVwV/pT3M1MgEK6CB3ebGAgzZeSA+8ZViWwEimm6YZfyUnacwZz3E92pfA=
  on:
    tags: true
    repo: yulkes/image-builder-lib
    python: 3.6
